"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Sparkles, Loader2, FileText, Download, CheckCircle2 } from "lucide-react";
import { toast } from "sonner";
import { api, type RP, type BriefingResponse } from "@/lib/api";
import { exportRiskBriefingPDF } from "@/lib/pdfGenerator";

export function RiskBriefing({
  scenario = "100y",
  portfolioLossKes = 164714571.5,
  lossRatio = 0.00259,
  keyHotspots = ["Mathare", "Kibera", "Industrial Area", "Dandora"],
}: {
  scenario?: RP;
  portfolioLossKes?: number;
  lossRatio?: number;
  keyHotspots?: string[];
}) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [briefing, setBriefing] = useState<BriefingResponse | null>(null);

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      const res = await api.briefing({
        scenario,
        portfolio_loss_kes: portfolioLossKes,
        loss_ratio: lossRatio,
        key_hotspots: keyHotspots,
        ai_enabled: true,
      });
      setBriefing(res);
      toast.success("Executive Risk Briefing generated by Groq (openai/gpt-oss-120b)!");
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to generate risk briefing");
    } finally {
      setIsGenerating(false);
    }
  };

  const [isDownloadingPdf, setIsDownloadingPdf] = useState(false);

  const handleDownload = async () => {
    if (!briefing) return;
    try {
      setIsDownloadingPdf(true);
      await exportRiskBriefingPDF(briefing, scenario);
      toast.success("Kenya Re Executive Memorandum PDF downloaded!");
    } catch (err) {
      console.error(err);
      toast.error("Failed to generate PDF memorandum.");
    } finally {
      setIsDownloadingPdf(false);
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-lg font-bold text-[#00264D] mb-1 flex items-center gap-2">
          <Sparkles className="size-5 text-[#D21245]" />
          Executive Risk Briefing Generator (Groq LLM)
        </h3>
        <p className="text-sm text-slate-600">
          Synthesizes modeled portfolio losses, drainage bottleneck exposures, and reinsurance treaty recommendations for executive committees.
        </p>
      </div>

      <Button
        onClick={handleGenerate}
        disabled={isGenerating}
        className="w-full bg-[#D21245] hover:bg-[#B50F3B] text-white"
      >
        {isGenerating ? (
          <>
            <Loader2 className="size-4 mr-2 animate-spin" />
            Analyzing with Groq (openai/gpt-oss-120b)...
          </>
        ) : (
          <>
            <Sparkles className="size-4 mr-2" />
            Generate Actuarial Risk Briefing
          </>
        )}
      </Button>

      {briefing && (
        <div className="space-y-4">
          <div className="rounded-lg border border-slate-200 bg-white p-3.5 sm:p-5 space-y-4 shadow-sm">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-3 border-b border-slate-100">
              <div className="flex items-center gap-2">
                <FileText className="size-5 text-[#00264D] shrink-0" />
                <span className="font-semibold text-slate-900 text-sm sm:text-base">Executive Memorandum ({scenario})</span>
              </div>
              <Button
                size="sm"
                onClick={handleDownload}
                disabled={isDownloadingPdf}
                className="gap-2 w-full sm:w-auto bg-[#00264D] hover:bg-[#001830] text-white cursor-pointer"
              >
                {isDownloadingPdf ? (
                  <>
                    <Loader2 className="size-4 animate-spin" />
                    Generating PDF...
                  </>
                ) : (
                  <>
                    <Download className="size-4" />
                    Download Official PDF Memorandum
                  </>
                )}
              </Button>
            </div>

            <div>
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-1.5">Executive Summary</h4>
              <p className="text-sm text-slate-800 leading-relaxed bg-slate-50 p-3.5 rounded border border-slate-100">
                {briefing.executive_summary}
              </p>
            </div>

            <div>
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-1.5">Key Findings</h4>
              <ul className="space-y-1.5 text-sm text-slate-700">
                {briefing.key_findings.map((f, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-[#00264D] font-bold shrink-0">{i + 1}.</span>
                    <span>{f}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div>
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-1.5">Actuarial Recommendations</h4>
              <ul className="space-y-1.5 text-sm text-slate-700">
                {briefing.recommendations.map((r, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <CheckCircle2 className="size-4 text-emerald-600 shrink-0 mt-0.5" />
                    <span>{r}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="pt-2 text-[11px] text-slate-400 italic">
              {briefing.disclaimer}
            </div>
          </div>

          <div className="flex gap-2">
            <Button
              variant="outline"
              onClick={() => setBriefing(null)}
              className="flex-1"
            >
              Clear
            </Button>
            <Button
              onClick={handleGenerate}
              className="flex-1 bg-[#00264D] hover:bg-[#001830] text-white"
            >
              Regenerate Briefing
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
