"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Sparkles, Loader2, FileText, Download } from "lucide-react";
import { toast } from "sonner";

export function RiskBriefing() {
  const [isGenerating, setIsGenerating] = useState(false);
  const [briefing, setBriefing] = useState<string | null>(null);

  const handleGenerate = () => {
    setIsGenerating(true);

    // Simulate AI generation
    setTimeout(() => {
      setBriefing(`# Nairobi Urban Flood Risk Assessment Brief

## Executive Summary
This portfolio of 600 synthetic properties across Nairobi County represents a total insured value (TIV) of KES 4.82 billion. The portfolio is concentrated in high-risk flood zones including Kayole, Mathare, and Dandora.

## Key Risk Metrics
- **Total Insured Value:** KES 4.82 billion
- **Average Annual Loss (AAL):** KES 94.2 million (1.95% of TIV)
- **1-in-100 Year PML:** KES 842.6 million (17.5% of TIV)
- **1-in-10 Year Loss:** KES 238.9 million (4.95% of TIV)

## Risk Concentration Analysis
The portfolio shows significant accumulation in informal settlements along river valleys:
- **Informal Iron Sheet (15% of TIV):** 42% of total expected loss
- **Semi-Permanent (25% of TIV):** 28% of total expected loss
- **Permanent Masonry (40% of TIV):** 20% of total expected loss
- **Concrete RCC (20% of TIV):** 10% of total expected loss

## AI-Enhanced Insights
Our AI drainage-gap detection has identified an additional KES 115 million of modeled capital exposure in 12 drainage-failure zones (Kibera, Westlands, Lavington) that terrain-only models miss.

## Recommendations
1. **Portfolio Diversification:** Consider reducing exposure in informal iron-sheet constructions
2. **Sub-Limit Implementation:** Implement 10% sub-limit on iron-sheet assets
3. **Reinsurance Layering:** Attach XOL treaty at 1-in-10 year level (KES 238.9M)
4. **Premium Adjustment:** Apply risk loading for high-concentration zones

---
*Generated by Kenya Re CAT Risk Intelligence Platform*
*Model Version: Nairobi Pluvial v1.0*
*Date: ${new Date().toLocaleDateString()}*`);
      setIsGenerating(false);
      toast.success("Risk briefing generated successfully!");
    }, 2500);
  };

  const handleDownload = () => {
    if (!briefing) return;

    const blob = new Blob([briefing], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `risk-briefing-${new Date().toISOString().split("T")[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast.success("Briefing downloaded!");
  };

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-lg font-bold text-[#00264D] mb-2">AI Risk Briefing Generator</h3>
        <p className="text-sm text-slate-600">
          Generate an executive risk summary for underwriting teams and reinsurance placement.
        </p>
      </div>

      <Button
        onClick={handleGenerate}
        disabled={isGenerating}
        className="w-full bg-[#D21245] hover:bg-[#B50F3B]"
      >
        {isGenerating ? (
          <>
            <Loader2 className="size-4 mr-2 animate-spin" />
            Generating with AI...
          </>
        ) : (
          <>
            <Sparkles className="size-4 mr-2" />
            Generate Risk Briefing
          </>
        )}
      </Button>

      {briefing && (
        <div className="space-y-4">
          <div className="rounded-lg border border-slate-200 bg-white p-4">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <FileText className="size-5 text-[#00264D]" />
                <span className="font-semibold text-slate-900">Generated Briefing</span>
              </div>
              <Button
                variant="outline"
                size="sm"
                onClick={handleDownload}
                className="gap-2"
              >
                <Download className="size-4" />
                Download
              </Button>
            </div>
            <Textarea
              value={briefing}
              readOnly
              className="min-h-[400px] font-mono text-sm bg-slate-50"
            />
          </div>

          <div className="flex gap-2">
            <Button
              variant="outline"
              onClick={() => setBriefing(null)}
              className="flex-1"
            >
              Clear
            </Button>
            <Button
              onClick={handleGenerate}
              className="flex-1 bg-[#00264D] hover:bg-[#001830]"
            >
              Regenerate
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
